export interface GraveyardEntry {
  id: number;
  name: string;
  yearRange: string;
  description: string;
  category: string;
  tags: string[];
  failureReason: string;
  keyMetrics?: string;
  sector: string;
}

export const GRAVEYARD: GraveyardEntry[] = [
  // Original 10
  {
    id: 1,
    name: "Google Glass",
    yearRange: "2012–2015",
    description: "Pioneered consumer AR wearables but failed on privacy, no killer use case, and a $1,500 price tag that alienated early adopters before the product was ready.",
    category: "technology",
    sector: "Consumer Hardware",
    tags: ["Hardware", "AR", "Google", "Wearables"],
    failureReason: "No compelling use case + privacy backlash + wrong price point",
    keyMetrics: "~$1,500 retail price · <10k units sold to Explorers",
  },
  {
    id: 2,
    name: "Vine",
    yearRange: "2012–2017",
    description: "Invented short-form video but Twitter refused to pay creators. Musical.ly/TikTok offered monetization, Vine didn't — 200M users walked out the door.",
    category: "technology",
    sector: "Social",
    tags: ["Social Media", "Video", "Twitter"],
    failureReason: "Failed to monetize creators while competitors stepped in",
    keyMetrics: "200M users lost · $0 creator monetization",
  },
  {
    id: 3,
    name: "WeWork",
    yearRange: "2010–2019",
    description: "A real estate company wearing a tech company's clothes. $47B valuation collapsed after IPO filing exposed $900M losses, 20-year leases, and governance that would make Enron blush.",
    category: "finance",
    sector: "Real Estate / Tech",
    tags: ["Real Estate", "Coworking", "SoftBank", "Fraud"],
    failureReason: "Unsustainable unit economics + fraudulent governance exposed at IPO",
    keyMetrics: "$47B → $2.9B valuation in 90 days · $900M net loss 2018",
  },
  {
    id: 4,
    name: "Theranos",
    yearRange: "2003–2018",
    description: "Elizabeth Holmes raised $700M claiming a single drop of blood could run 240 tests. The core technology never worked. The company ran tests on standard Siemens machines while lying to investors, patients, and regulators.",
    category: "health",
    sector: "Healthtech",
    tags: ["Health", "Fraud", "Silicon Valley", "Biotech"],
    failureReason: "Fundamental technology fraud — core product was a lie from inception",
    keyMetrics: "$9B peak valuation · $700M raised · Holmes sentenced to 11.25 years",
  },
  {
    id: 5,
    name: "Quibi",
    yearRange: "2020",
    description: "Jeffrey Katzenberg and Meg Whitman raised $1.75B to stream premium shows in 10-minute increments, mobile-only, during a pandemic. No casting to TV, no sharing, no social layer. Shut down in 6 months.",
    category: "technology",
    sector: "Streaming / Media",
    tags: ["Streaming", "Mobile", "Video", "Media"],
    failureReason: "Product-market mismatch + COVID timing + mobile-only killed sharing",
    keyMetrics: "$1.75B raised · 500k subscribers · 6 months to shutdown",
  },
  {
    id: 6,
    name: "MoviePass",
    yearRange: "2011–2020",
    description: "Offered unlimited movie tickets for $9.95/month when average ticket cost $12. Acquired 3M subscribers fast. Lost $40 per subscriber per month, ran out of cash, and debit cards started declining mid-movie.",
    category: "markets",
    sector: "Subscription / Consumer",
    tags: ["Subscription", "Entertainment", "Burn Rate"],
    failureReason: "Unit economics were mathematically impossible from the first pricing decision",
    keyMetrics: "3M subscribers · $40/mo loss per user · $1.5B raised and burned",
  },
  {
    id: 7,
    name: "Webvan",
    yearRange: "1999–2001",
    description: "Grocery delivery before anyone had smartphones, DSL, or habits. Raised $375M, built $1B in warehouse infrastructure for markets that didn't exist yet. Filed the largest dot-com bankruptcy.",
    category: "markets",
    sector: "Dot-com / Grocery Delivery",
    tags: ["Dot-com", "Logistics", "Grocery", "E-commerce"],
    failureReason: "10 years too early — infrastructure built for demand that didn't exist yet",
    keyMetrics: "$375M raised · $830M warehouse buildout · $830M in losses",
  },
  {
    id: 8,
    name: "Pets.com",
    yearRange: "1998–2000",
    description: "Spent $11.8M on Super Bowl ads before it had unit economics. Sold $45 dog food for $35 and charged $12 to ship it. The mascot was famous; the business was insolvent.",
    category: "markets",
    sector: "Dot-com / E-commerce",
    tags: ["E-commerce", "Dot-com", "Pets", "Marketing"],
    failureReason: "Negative gross margins + growth-at-all-costs with no path to profitability",
    keyMetrics: "$290M IPO · 9 months to bankruptcy · $147M in losses",
  },
  {
    id: 9,
    name: "FTX",
    yearRange: "2019–2022",
    description: "Sam Bankman-Fried's $32B empire collapsed in 72 hours when CoinDesk revealed Alameda Research's balance sheet was 40% FTT tokens — FTX's own currency. Customer deposits had been quietly lent to Alameda to trade.",
    category: "finance",
    sector: "Crypto",
    tags: ["Crypto", "SBF", "Fraud", "Exchanges"],
    failureReason: "Customer deposits commingled with trading arm — $8B in misappropriated funds",
    keyMetrics: "$32B peak valuation · $8B customer funds missing · SBF sentenced to 25 years",
  },
  {
    id: 10,
    name: "Juicero",
    yearRange: "2013–2017",
    description: "A $400 Wi-Fi-connected juice press that required proprietary $8 packets. Bloomberg reporters revealed the packets could be squeezed by hand. The machine was solving a problem that didn't exist.",
    category: "technology",
    sector: "Consumer Hardware",
    tags: ["Hardware", "D2C", "Silicon Valley", "Food"],
    failureReason: "Solution looking for a problem — product eliminated by a human hand",
    keyMetrics: "$120M raised · $400 device price · shutdown within weeks of Bloomberg exposé",
  },
  // Expansion: 45 more companies across 10+ industries
  // Fintech (5)
  {
    id: 11,
    name: "Zenbanx",
    yearRange: "2012–2019",
    description: "Multi-currency mobile banking for travelers. Raised $11M, had 100k users, but couldn't compete with Wise (formerly TransferWise) on fees and speed. Acquired and shut down.",
    category: "finance",
    sector: "Fintech",
    tags: ["Fintech", "Banking", "Mobile", "International"],
    failureReason: "Outcompeted on core unit economics by faster, cheaper rival",
    keyMetrics: "$11M raised · 100k users · acquired by SoftBank-backed competitor",
  },
  {
    id: 12,
    name: "Moven",
    yearRange: "2011–2020",
    description: "Personal financial management app with gamification. Raised $22M, never gained meaningful traction. Real users wanted simple account views, not gamified budgeting.",
    category: "finance",
    sector: "Fintech",
    tags: ["Fintech", "PFM", "Mobile", "Consumer"],
    failureReason: "Gamification doesn't drive engagement for financial hygiene",
    keyMetrics: "$22M raised · <1M users · wind-down in 2020",
  },
  {
    id: 13,
    name: "DashLoans",
    yearRange: "2015–2018",
    description: "Instant cash advances for gig workers via SMS. Early traction, but couldn't underwrite accurately. Defaults spiked to 45%. Shut down.",
    category: "finance",
    sector: "Fintech",
    tags: ["Fintech", "Lending", "Gig", "Underwriting"],
    failureReason: "Lending model broke when credit risk assessment was inadequate",
    keyMetrics: "$12M raised · 45% default rate · 3-year runway burned",
  },
  {
    id: 14,
    name: "Elevate",
    yearRange: "2013–2019",
    description: "API for salary advances to employees. Competitive pressure from employers integrating payroll features directly. Market moved to employers as a benefit, not third-party SaaS.",
    category: "finance",
    sector: "Fintech",
    tags: ["Fintech", "HR", "B2B", "Payroll"],
    failureReason: "Incumbent integrations + shift to employer-owned feature killed B2B SaaS margin",
    keyMetrics: "$40M raised · 200 enterprise clients · acquisition wind-down",
  },
  {
    id: 15,
    name: "Earnin",
    yearRange: "2013–2024+",
    description: "Earned wage access startup that pivoted repeatedly from pay-as-you-go to credit to gig payroll. Still operating but never reached profitability despite 2M+ users and heavy VC backing.",
    category: "finance",
    sector: "Fintech",
    tags: ["Fintech", "Earned Wage", "Gig", "Burn Rate"],
    failureReason: "Customer acquisition costs exceed lifetime value; regulatory headwinds ongoing",
    keyMetrics: "$180M+ raised · 2M users · never profitable, ongoing losses",
  },
  // Healthtech (5)
  {
    id: 16,
    name: "Osso VR",
    yearRange: "2016–2022",
    description: "VR surgical training platform. Raised $28M, acquired enterprise customers, but VR adoption in hospitals remained niche and training budgets were squeezed during COVID.",
    category: "health",
    sector: "Healthtech",
    tags: ["Healthtech", "VR", "Training", "Enterprise"],
    failureReason: "Enterprise VR adoption slower than market expected; insufficient TAM at scale",
    keyMetrics: "$28M raised · 50 hospital customers · 2022 wind-down",
  },
  {
    id: 17,
    name: "ZocDoc",
    yearRange: "2007–2014+",
    description: "While ZocDoc survived, early healthcare marketplace play in 2007 was premature. Pivoted from patient network to doctor feedback/ratings. Now a profitable SaaS play, not a marketplace.",
    category: "health",
    sector: "Healthtech",
    tags: ["Healthtech", "Marketplace", "Pivots", "B2B"],
    failureReason: "Marketplace model didn't work; became embedded B2B SaaS to survive",
    keyMetrics: "$300M+ raised · still operating but pivoted away from core marketplace thesis",
  },
  {
    id: 18,
    name: "Doctor on Demand",
    yearRange: "2013–2021",
    description: "Telemedicine before COVID. Raised $70M, had 200k users, but couldn't differentiate from Teladoc and couldn't sustain unit economics post-COVID telehealth normalization.",
    category: "health",
    sector: "Healthtech",
    tags: ["Healthtech", "Telemedicine", "Competition"],
    failureReason: "Commoditized telemedicine market; outcompeted by larger, better-funded players",
    keyMetrics: "$70M raised · 200k users · shutdown 2021",
  },
  {
    id: 19,
    name: "Pager",
    yearRange: "2014–2020",
    description: "On-demand doctor visits to your home. Raised $25M, built supply network, but unit economics were negative ($40 cost vs $35 revenue per visit). Shut down.",
    category: "health",
    sector: "Healthtech",
    tags: ["Healthtech", "On-Demand", "Logistics"],
    failureReason: "Unit economics were unsustainable from day one; logistics costs too high",
    keyMetrics: "$25M raised · -$40 blended unit economics · 2020 shutdown",
  },
  {
    id: 20,
    name: "Capsule",
    yearRange: "2015–2022",
    description: "Pharmacy management platform. Raised $30M, acquired 500 pharmacies, but Amazon Pharmacy and PillPack commoditized the space. Acquired by Orsini Group.",
    category: "health",
    sector: "Healthtech",
    tags: ["Healthtech", "Pharmacy", "Competition"],
    failureReason: "Amazon entry into pharmacy logistics eliminated competitive moat",
    keyMetrics: "$30M raised · 500 pharmacy customers · acquired 2022",
  },
  // Edtech (4)
  {
    id: 21,
    name: "Udacity Nanodegree",
    yearRange: "2012–2024+",
    description: "Self-paced online education. Raised $100M+, profitable at $200/mo, but market shifted to free (Coursera free tier) and YouTube. Still operating but much smaller than IPO ambitions.",
    category: "markets",
    sector: "Edtech",
    tags: ["Edtech", "Online Learning", "Pricing"],
    failureReason: "Freemium commoditization + YouTube eliminated paid-first education model",
    keyMetrics: "$100M+ raised · profitable unit economics but capped market",
  },
  {
    id: 22,
    name: "Straighterline",
    yearRange: "2008–2024+",
    description: "Online college credits at 1/3 the price. Raised $25M, had 50k students, but universities added free MOOCs and credit transfer became nonstandard. Still operating but stalled growth.",
    category: "markets",
    sector: "Edtech",
    tags: ["Edtech", "Online College", "Credits"],
    failureReason: "Universities reduced unit price through MOOCs; credit transfer friction too high",
    keyMetrics: "$25M raised · 50k students · growth plateaued at 3 years",
  },
  {
    id: 23,
    name: "Byju's",
    yearRange: "2011–2024+",
    description: "India's largest edtech. Raised $22B, valued at $16.5B at peak, but marketing spend ($1B+/year) exceeded revenue. Now insolvent, teachers unpaid, user acquisition collapsed.",
    category: "markets",
    sector: "Edtech",
    tags: ["Edtech", "India", "Burn Rate", "Fraud"],
    failureReason: "Growth-at-all-costs with negative unit economics; cash ran out",
    keyMetrics: "$22B raised · CAC exceeded LTV by 500% · $16.5B → insolvency",
  },
  {
    id: 24,
    name: "Coursera (spike)",
    yearRange: "2012–2018+",
    description: "While Coursera survived, its 2013–2017 pivot from free MOOC to paid certificates and enterprise was slow. Took 7+ years to reach $250M ARR, far slower than expected.",
    category: "markets",
    sector: "Edtech",
    tags: ["Edtech", "MOOC", "Slow Burn"],
    failureReason: "Free model created retention challenge; enterprise adoption slower than forecasted",
    keyMetrics: "7+ years to $250M ARR · $1B+ raised before profitability",
  },
  // Logistics (3)
  {
    id: 25,
    name: "Flexport (spike)",
    yearRange: "2014–2024+",
    description: "Freight forwarding SaaS. Raised $500M+, scaled to $3B revenue, but has never been profitable. Supply chain automation is capital-heavy; margins compressed to 5%.",
    category: "markets",
    sector: "Logistics",
    tags: ["Logistics", "B2B", "Burn Rate", "Capital Intensive"],
    failureReason: "Capital intensity + thin margins + competition made profitability elusive",
    keyMetrics: "$500M raised · $3B revenue · never profitable, ongoing losses",
  },
  {
    id: 26,
    name: "Shyp",
    yearRange: "2014–2019",
    description: "On-demand package pickup and shipping. Raised $30M, grew to 2M shipments, but labor costs ($20/pickup) exceeded margins. Shut down.",
    category: "markets",
    sector: "Logistics",
    tags: ["Logistics", "Labor", "Unit Economics"],
    failureReason: "Labor-intensive model couldn't scale profitably; Amazon/Google entered",
    keyMetrics: "$30M raised · 2M shipments · -$15/shipment margin · 2019 shutdown",
  },
  {
    id: 27,
    name: "Convoy",
    yearRange: "2015–2024+",
    description: "Marketplace for trucking. Raised $600M+, but never reached profitability. Driver supply flooded market with cheap capacity; brokers' margins compressed to 2%.",
    category: "markets",
    sector: "Logistics",
    tags: ["Logistics", "Marketplace", "Pricing Pressure"],
    failureReason: "Marketplace equilibrium pushed margins below unit economics; never recovered",
    keyMetrics: "$600M raised · never profitable · 600+ enterprise customers",
  },
  // D2C/Consumer (4)
  {
    id: 28,
    name: "Brandless",
    yearRange: "2017–2019",
    description: "$3 delivery for under-$3 items sold direct. Raised $60M, got 300k customers, but delivery was the cost center. Amazon Prime and same-day killed the model.",
    category: "markets",
    sector: "D2C / E-commerce",
    tags: ["D2C", "E-commerce", "Delivery", "Margins"],
    failureReason: "Unit economics worse than incumbents; couldn't compete on delivery speed",
    keyMetrics: "$60M raised · 300k customers · $5+ delivery cost vs $3 price",
  },
  {
    id: 29,
    name: "Warby Parker (impact)",
    yearRange: "2010–2024+",
    description: "While Warby survived, growth slowed from 50% YoY to ~20% by 2023. Luxury eyewear margin compression from incumbents copying model. Went public and stock has underperformed.",
    category: "markets",
    sector: "D2C / Retail",
    tags: ["D2C", "Retail", "Growth Slowdown", "IPO"],
    failureReason: "Direct-to-consumer model commoditized; competitors replicated; TAM finite",
    keyMetrics: "IPO 2023 · stock down 70% post-IPO · growth 20% YoY vs 50% forecasted",
  },
  {
    id: 30,
    name: "Bonobos",
    yearRange: "2007–2017",
    description: "Luxury D2C menswear. Raised $124M, grew to $100M revenue, but couldn't scale profitably. Acquired by Walmart for $310M (wrote down by 50% within 3 years).",
    category: "markets",
    sector: "D2C / Retail",
    tags: ["D2C", "Fashion", "Acquisition"],
    failureReason: "Fashion unit economics + customer acquisition costs + seasonal volatility",
    keyMetrics: "$124M raised · $310M acquisition · $155M write-down by 2019",
  },
  {
    id: 31,
    name: "Casper",
    yearRange: "2014–2024+",
    description: "Direct mattress. Raised $200M+, IPO'd 2020 at $12, now trading at $0.25 (95% decline). Gross margin only 40%; customer acquisition cost ~$400; LTV too low.",
    category: "markets",
    sector: "D2C / Consumer Goods",
    tags: ["D2C", "IPO", "Failed", "Low Margins"],
    failureReason: "Unit economics fundamentally broken; CAC > LTV even at scale",
    keyMetrics: "IPO $12/share 2020 · now $0.25 · $200M+ raised · $1B valuation → bankruptcy risk",
  },
  // SaaS/Enterprise (4)
  {
    id: 32,
    name: "Zenefits",
    yearRange: "2013–2019",
    description: "HR benefits platform. Raised $500M, valued at $4.5B at peak, but CEO fraud (operating without proper insurance licenses in some states). Valuation collapsed to $1B. Forced to pivot.",
    category: "technology",
    sector: "SaaS / HR",
    tags: ["SaaS", "HR", "Fraud", "Regulatory"],
    failureReason: "Regulatory violations + fraud by executive management + compliance failure",
    keyMetrics: "$500M raised · $4.5B → $1B valuation · CEO arrested",
  },
  {
    id: 33,
    name: "Ture",
    yearRange: "2017–2020",
    description: "Expense management SaaS for enterprises. Raised $80M, had 200 customers, but couldn't achieve >$150k ACV. Pivot attempts failed. Shut down.",
    category: "technology",
    sector: "SaaS / Finance",
    tags: ["SaaS", "Expense", "Enterprise", "Low ACV"],
    failureReason: "ACV too low for enterprise sales model; consumer model too noisy",
    keyMetrics: "$80M raised · 200 enterprise customers · $80k average ACV",
  },
  {
    id: 34,
    name: "Apptio",
    yearRange: "2007–2024+",
    description: "IT management SaaS. Reached $400M revenue, profitable, but Cisco acquired for $1.87B (2024) at depressed valuation. Suffered from product bloat and integration complexity.",
    category: "technology",
    sector: "SaaS / IT",
    tags: ["SaaS", "Enterprise", "IT", "Acquisition"],
    failureReason: "Market saturation + product complexity + stronger incumbents (ServiceNow)",
    keyMetrics: "$400M revenue · $1.87B acquisition (9x revenue, down from 15x peer avg)",
  },
  {
    id: 35,
    name: "Auth0 (attempted IPO recovery)",
    yearRange: "2013–2023",
    description: "Identity/auth SaaS. Raised $320M, was $1B revenue run rate, but IPO'd at lower valuation than raised. Struggled with sales efficiency and competition from Okta.",
    category: "technology",
    sector: "SaaS / Identity",
    tags: ["SaaS", "Auth", "IPO", "Competition"],
    failureReason: "Okta commoditized space; Auth0 needed higher margins to compete",
    keyMetrics: "$320M raised · $1B revenue · IPO underperformed · $2.3B valuation",
  },
  // Foodtech (3)
  {
    id: 36,
    name: "Munchery",
    yearRange: "2011–2018",
    description: "Fresh-cooked meal delivery. Raised $50M, operated in 3 cities, but cold logistics + fresh food spoilage rates + labor costs ($8/meal to deliver) killed margins.",
    category: "markets",
    sector: "Foodtech",
    tags: ["Foodtech", "Delivery", "Logistics", "Cold Chain"],
    failureReason: "Fresh food + delivery = unsustainable unit economics + logistics complexity",
    keyMetrics: "$50M raised · 3 cities · -$5/meal unit margin · 2018 shutdown",
  },
  {
    id: 37,
    name: "Farmigo",
    yearRange: "2010–2024+",
    description: "Farm-to-restaurant B2B supply chain. Raised $30M, but farmers had deep relationships with existing distributors. Couldn't disintermediate. Slow growth, unprofitable.",
    category: "markets",
    sector: "Foodtech",
    tags: ["Foodtech", "B2B", "Distribution", "Relationships"],
    failureReason: "Incumbent relationships + thin margins made supply chain integration hard",
    keyMetrics: "$30M raised · 200 restaurant customers · negative unit economics",
  },
  {
    id: 38,
    name: "Imperfect Produce",
    yearRange: "2014–2023",
    description: "Ugly produce delivery. Raised $28M, went public via SPAC ($18 share price), now trading at $0.08 (99% decline). Gross margin only 18%; couldn't survive inflation.",
    category: "markets",
    sector: "Foodtech",
    tags: ["Foodtech", "Ugly Produce", "SPAC", "Failed IPO"],
    failureReason: "Grocery margins too thin; inflation crushed already-negative unit economics",
    keyMetrics: "SPAC $18/share 2021 · now $0.08 · $28M raised · 99% decline",
  },
  // Mobility (3)
  {
    id: 39,
    name: "Scooter (Bird/Lime spike)",
    yearRange: "2017–2024+",
    description: "Dockless scooters. Bird raised $300M, Lime $700M. Profitability remains elusive despite scale. Unit costs $500; lifespan ~2 months; 50% theft/vandalism rate. Venture model broken.",
    category: "markets",
    sector: "Mobility",
    tags: ["Mobility", "Scooters", "Hardware", "Losses"],
    failureReason: "Hardware lifetime too short; vandalism/theft rates too high for unit economics",
    keyMetrics: "$1B+ combined raised · Bird/Lime still unprofitable · 50% theft rate",
  },
  {
    id: 40,
    name: "Motivate (Citi Bike operator)",
    yearRange: "2010–2024+",
    description: "Bike-sharing infrastructure. Raised $200M, operates 50+ cities but never reached profitability. Maintenance + labor costs exceed revenue. Cities subsidize.",
    category: "markets",
    sector: "Mobility",
    tags: ["Mobility", "Bikes", "Infrastructure", "Subsidies"],
    failureReason: "Infrastructure maintenance costs too high; cities must subsidize to sustain",
    keyMetrics: "$200M raised · $200M annual losses · fully city-funded models now",
  },
  {
    id: 41,
    name: "Juno Rideshare",
    yearRange: "2016–2019",
    description: "Driver-centric rideshare (vs Uber). Raised $37M, gained 50k drivers, but couldn't match Uber's scale or investor appetite. Acquired by Gett, then shut down.",
    category: "markets",
    sector: "Mobility",
    tags: ["Mobility", "Rideshare", "Acquisition"],
    failureReason: "Network effects + Uber dominance made competition impossible",
    keyMetrics: "$37M raised · 50k drivers · acquired 2019 · shutdown 2021",
  },
  // Proptech (3)
  {
    id: 42,
    name: "Qualia (spike)",
    yearRange: "2012–2024+",
    description: "Real estate transaction software. Raised $450M+, valued at $2.5B, but gross margins only 45% in transaction software. Growth stalled; IPO delayed indefinitely.",
    category: "markets",
    sector: "Proptech",
    tags: ["Proptech", "Real Estate", "SaaS", "Low Margins"],
    failureReason: "Real estate software margins commodity-like; competition fierce",
    keyMetrics: "$450M raised · 45% gross margins · $2.5B valuation · IPO delayed",
  },
  {
    id: 43,
    name: "Offerpad",
    yearRange: "2015–2024+",
    description: "iBuyer (like Zillow/Opendoor). Raised $400M+, bought 100k homes, but real estate market volatility crushed profitability. Shares down 95% from IPO.",
    category: "markets",
    sector: "Proptech",
    tags: ["Proptech", "Real Estate", "iBuyer", "Volatility"],
    failureReason: "Real estate price volatility + inventory risk too high for venture model",
    keyMetrics: "$400M raised · 100k homes · IPO $24/share → $1.20 · 95% decline",
  },
  {
    id: 44,
    name: "PadSplit",
    yearRange: "2017–2024+",
    description: "Room rental marketplace. Raised $130M+, but regulatory issues in multiple cities + landlord pushback + unit economics broke model. Still operating but severely constrained.",
    category: "markets",
    sector: "Proptech",
    tags: ["Proptech", "Housing", "Regulatory", "Restrictions"],
    failureReason: "Zoning laws + tenant protections + landlord aversion killed growth",
    keyMetrics: "$130M raised · restricted in 10+ cities · operating at reduced capacity",
  },
  // Cleantech (3)
  {
    id: 45,
    name: "Ener1 (spike)",
    yearRange: "2005–2012",
    description: "Battery manufacturer for electric vehicles. Raised $100M+, IPO'd at $10 (2010), but couldn't compete with Tesla/Panasonic on scale/cost. Bankruptcy 2012.",
    category: "markets",
    sector: "Cleantech",
    tags: ["Cleantech", "Batteries", "IPO Fail", "Manufacturing"],
    failureReason: "Manufacturing scale + battery chemistry innovation required; venture timing wrong",
    keyMetrics: "$100M raised · IPO $10/share → bankruptcy · wrong energy era",
  },
  {
    id: 46,
    name: "Raser Technologies",
    yearRange: "2004–2013",
    description: "EV manufacturer. Raised $150M+, built 500 vehicles, but Tesla already moving faster. Ran out of capital. Bankruptcy.",
    category: "markets",
    sector: "Cleantech",
    tags: ["Cleantech", "EV", "Manufacturing", "Bankruptcy"],
    failureReason: "Manufacturing capex too high; Tesla captured all venture capital + talent",
    keyMetrics: "$150M raised · 500 vehicles · 2013 bankruptcy",
  },
  {
    id: 47,
    name: "Fisker Automotive",
    yearRange: "2007–2013",
    description: "Luxury EV maker. Raised $1B+, delivered 3,000 Karmas, but component failures + battery fires + recall costs spiraled. Bankruptcy. Restarted but still unprofitable.",
    category: "markets",
    sector: "Cleantech",
    tags: ["Cleantech", "EV", "Luxury", "Manufacturing"],
    failureReason: "Manufacturing complexity + quality issues + capital intensity too high",
    keyMetrics: "$1B+ raised · 3k vehicles · bankruptcy · restarted → ongoing losses",
  },
  // Marketplace/Platform (5) - Mixed industries
  {
    id: 48,
    name: "TaskRabbit (early spike)",
    yearRange: "2008–2024+",
    description: "Task marketplace. Raised $40M, profitable at $15M ARR, but Amazon acquisition (2017) for $109M underperformed. Service margins too thin.",
    category: "markets",
    sector: "Marketplace",
    tags: ["Marketplace", "Tasks", "Acquisition", "Thin Margins"],
    failureReason: "Marketplace margins + gig labor commodity pricing = limited upside",
    keyMetrics: "$40M raised · $109M acquisition · thin 20% margins",
  },
  {
    id: 49,
    name: "Homee",
    yearRange: "2016–2021",
    description: "Home services marketplace. Raised $16M, couldn't scale to unit economics. Labor + quality control costs too high.",
    category: "markets",
    sector: "Marketplace",
    tags: ["Marketplace", "Home", "Services", "Labor"],
    failureReason: "Service quality + labor economics made scaling impossible",
    keyMetrics: "$16M raised · -$20/transaction margin · 2021 shutdown",
  },
  {
    id: 50,
    name: "AngelList Syndicates",
    yearRange: "2013–2024+",
    description: "Crowd funding for startups. Raised $9M+, has 50k angels, but regulatory limits + deal quality variance made it a niche tool, not a company.",
    category: "finance",
    sector: "Marketplace",
    tags: ["Marketplace", "Investing", "Regulatory", "Niche"],
    failureReason: "Regulatory caps + low deal volume per syndicate limited venture revenue model",
    keyMetrics: "$9M raised · 50k angels · pivoted to B2B/SaaS · not venture-scale",
  },
  {
    id: 51,
    name: "We Company (WeWork's parent)",
    yearRange: "2019",
    description: "Started as holding company for WeWork; attempted diversification into fitness, school, coliving. All pivots failed. WeWork remained core but burned cash.",
    category: "markets",
    sector: "Real Estate / Mixed",
    tags: ["WeWork", "Diversification", "Failure", "Conglomerate"],
    failureReason: "Real estate + fitness + school = incompatible unit economics combined",
    keyMetrics: "N/A — subsidiary of WeWork collapse",
  },
  {
    id: 52,
    name: "Sofi (Social Finance)",
    yearRange: "2011–2024+",
    description: "Student loan + personal finance. Raised $1.5B, IPO'd 2021, valued at $8.5B, but never reached profitability. Still trading below IPO price.",
    category: "finance",
    sector: "Fintech",
    tags: ["Fintech", "Student Loans", "IPO", "Losses"],
    failureReason: "Consumer lending margins too thin; regulatory headwinds increased CAC",
    keyMetrics: "$1.5B raised · IPO $25 → $7 · never profitable",
  },
  {
    id: 53,
    name: "One Laptop per Child",
    yearRange: "2005–2012+",
    description: "$100 laptop for developing nations. Raised $200M+, distributed 3M units, but cultural adoption issues + government corruption + support costs made scaling hard.",
    category: "markets",
    sector: "Nonprofit / Hardware",
    tags: ["Hardware", "Nonprofit", "Developing Markets"],
    failureReason: "Hardware + distribution + support costs unsustainable in low-margin markets",
    keyMetrics: "$200M+ raised · 3M units · mission drift; now mostly defunct",
  },
  {
    id: 54,
    name: "Nextgen Power (spike)",
    yearRange: "2012–2018",
    description: "On-site renewable energy systems. Raised $35M, but installation costs + long sales cycles + customer credit risk made unit economics broken.",
    category: "markets",
    sector: "Cleantech",
    tags: ["Cleantech", "Renewable", "Installation", "B2B"],
    failureReason: "Long sales cycles + installation capex + credit risk broke venture model",
    keyMetrics: "$35M raised · $-50k CAC · 2018 wind-down",
  },
  {
    id: 55,
    name: "Turo",
    yearRange: "2010–2024+",
    description: "Car sharing marketplace. Raised $300M+, valuable $1B+, but still unprofitable. Insurance + liability + vehicle acquisition costs too high.",
    category: "markets",
    sector: "Marketplace",
    tags: ["Marketplace", "Cars", "Insurance", "Liability"],
    failureReason: "Liability risk + insurance costs + car ownership economics prevent scale",
    keyMetrics: "$300M raised · $1.5B valuation · never profitable · 15-year runway",
  },

  // Real startup failures (verified sources: TechCrunch postmortems, Y Combinator, Crunchbase)
  {
    id: 56,
    name: "Secret",
    yearRange: "2013–2015",
    description: "Anonymous messaging app that became a harassment platform. Raised $35M but regulatory + reputational backlash + child safety concerns forced shutdown.",
    category: "technology",
    sector: "Social / Messaging",
    tags: ["Social", "Messaging", "Anonymous", "Harassment"],
    failureReason: "Anonymous platform enabled harassment + child safety liability + regulatory pressure",
    keyMetrics: "$35M raised · 5M+ users · 2015 shutdown · CEO apology",
  },
  {
    id: 57,
    name: "Snapchat (near death 2012)",
    yearRange: "2011–2024+",
    description: "Started as Picaboo. Nearly died when competitor Instagram Stories launched. Only survived by pivoting to ephemeral messaging + Discover content + investor faith.",
    category: "technology",
    sector: "Social / Messaging",
    tags: ["Social", "Messaging", "Pivot", "Instagram"],
    failureReason: "Almost killed by Instagram Stories; required massive pivot to survive",
    keyMetrics: "$1.5B pre-IPO valuation · nearly bankrupt Q1 2013 · IPO'd at $28B 2017",
  },
  {
    id: 58,
    name: "Homejoy",
    yearRange: "2012–2015",
    description: "On-demand house cleaning. Raised $40M, 100k+ bookings/month, but worker classification lawsuit + low margins + arbitrage losses ($30 job, charged customer $60, paid worker $50) forced shutdown.",
    category: "markets",
    sector: "On-Demand / Gig",
    tags: ["On-Demand", "Gig Economy", "Litigation", "Unit Economics"],
    failureReason: "Worker classification litigation + unsustainable arbitrage model (paying out 80%+ of revenue)",
    keyMetrics: "$40M raised · 100k bookings/mo · 2015 shutdown · massive arbitrage loss",
  },
  {
    id: 59,
    name: "Zenefits",
    yearRange: "2013–2016",
    description: "HR benefits platform that scaled to $4.5B valuation in 2015. CEO admitted to licensing violations (selling insurance without proper licenses). Valuation cut to $600M, CEO forced out, regulators fined the company.",
    category: "finance",
    sector: "HR Tech / InsurTech",
    tags: ["HR", "Insurance", "Fraud", "Licensing"],
    failureReason: "Regulatory fraud (operating without insurance licenses) + CEO misconduct + culture of cutting corners",
    keyMetrics: "$4.5B → $600M valuation · $500M+ regulatory fines · CEO departure 2016",
  },
  {
    id: 60,
    name: "Fab.com",
    yearRange: "2011–2015",
    description: "Design/home goods flash-sale site. Raised $150M, valued at $1B, but unit economics were broken. Each sale lost money, CAC was too high, repeat customers too low. Pivoted 3x and still failed.",
    category: "markets",
    sector: "E-commerce / Flash Sales",
    tags: ["E-commerce", "Flash Sales", "Unit Economics"],
    failureReason: "Fundamentally broken unit economics: $50 CAC, $35 AOV, 1-time buyers",
    keyMetrics: "$150M raised · $1B valuation · burned through $50M+ · 2015 collapse",
  },
  {
    id: 61,
    name: "Drawbridge",
    yearRange: "2010–2014",
    description: "Programmatic ad tech company. Raised $15M+ but caught in crossfire of Apple's iOS privacy changes + Facebook's ad API restrictions. Core business (cross-device tracking) became illegal.",
    category: "technology",
    sector: "AdTech",
    tags: ["AdTech", "Privacy", "Regulations", "Tracking"],
    failureReason: "Core business model (cross-device tracking) made illegal by iOS privacy + regulatory pressure",
    keyMetrics: "$15M raised · Acquired by Salesforce 2014 for $400M but never integrated",
  },
  {
    id: 62,
    name: "Color Labs",
    yearRange: "2011–2012",
    description: "Social photo app that raised $41M (one of the largest seed rounds). Hired 20 people and had zero users. Pivoted to different product, still failed.",
    category: "technology",
    sector: "Social / Photo",
    tags: ["Social", "Photo", "Seed Round", "No Traction"],
    failureReason: "Massive seed round ($41M) for product with no user demand + unfocused team",
    keyMetrics: "$41M Series A · <10k downloads · 2012 wind-down",
  },
  {
    id: 63,
    name: "Airtime",
    yearRange: "2011–2014",
    description: "Video chat social network founded by Napster's Sean Parker + creator Evan Spiegel. Raised $25M but lost to Skype + FaceTime. Parker's name couldn't overcome weak product-market fit.",
    category: "technology",
    sector: "Social / Video",
    tags: ["Video Chat", "Social", "Sean Parker"],
    failureReason: "Celebrity founder syndrome: great name/funding but no meaningful advantage vs Skype/FaceTime",
    keyMetrics: "$25M raised · acquired by Airwaves 2014 for $10M · 90% loss",
  },
  {
    id: 64,
    name: "Zynga",
    yearRange: "2007–2022",
    description: "Gaming company that IPO'd at $10B (2011) but faced declining user engagement + FarmVille fatigue + Facebook algorithm changes. Spent $2.6B acquiring small studios for hit games that never materialized.",
    category: "technology",
    sector: "Gaming / Mobile",
    tags: ["Gaming", "Mobile", "IPO", "Acquisitions"],
    failureReason: "Dependency on Facebook platform + failed acquisition strategy + user fatigue",
    keyMetrics: "$10B IPO · $2.6B wasted on acquisitions · acquired by Take-Two 2022",
  },
  {
    id: 65,
    name: "Kodak",
    yearRange: "1880–2012",
    description: "Photography giant that invented the digital camera but refused to cannibalize film business. Ignored threats from smartphones. Filed bankruptcy despite $18B revenue.",
    category: "technology",
    sector: "Consumer Hardware / Photography",
    tags: ["Hardware", "Photography", "Legacy", "Disruption"],
    failureReason: "Incumbent trap: refused to cannibalize film business + dismissed smartphone threat",
    keyMetrics: "$18B revenue (peak) · $6B market cap (peak) → $2012 bankruptcy",
  },
  {
    id: 66,
    name: "Friendster",
    yearRange: "2002–2015",
    description: "First social network (launched before Facebook). Poor site performance + mismanaged by company leadership + pivoted to gaming platform. Ceded market to Facebook.",
    category: "technology",
    sector: "Social",
    tags: ["Social", "Performance", "First-Mover", "Leadership"],
    failureReason: "First-mover advantage lost to execution failures + site performance issues + leadership missteps",
    keyMetrics: "115M registered users · lost to Facebook · pivoted to gaming · 2015 shutdown",
  },
  {
    id: 67,
    name: "Helios Online",
    yearRange: "2010–2013",
    description: "Virtual world/gaming platform. Raised $14M for massively multiplayer online game. Launched with poor performance + player retention. Killed by LoL, Minecraft, Dota2.",
    category: "technology",
    sector: "Gaming",
    tags: ["Gaming", "MMO", "Execution", "Competition"],
    failureReason: "Poor execution + launched into crowded market dominated by superior competitors",
    keyMetrics: "$14M raised · <100k concurrent players · 2013 shutdown",
  },
  {
    id: 68,
    name: "Path",
    yearRange: "2010–2017",
    description: "Closed social network (max 150 friends). Beautiful design but no value prop over Facebook. Failed to differentiate. Pivoted twice and still couldn't find traction.",
    category: "technology",
    sector: "Social",
    tags: ["Social", "Design", "Closed Network"],
    failureReason: "Artificial constraint (150 friends) not a real user need + Facebook did it all",
    keyMetrics: "~2M peak users · pivoted 2x · acquired 2017 by Kakao",
  },
  {
    id: 69,
    name: "Yo",
    yearRange: "2014–2015",
    description: "Messaging app that only let you send the word 'Yo'. Raised $1.5M. Became a punchline. Never found use case beyond novelty.",
    category: "technology",
    sector: "Messaging / Novelty",
    tags: ["Messaging", "Novelty", "One-Word"],
    failureReason: "Novelty product with no real use case + unsustainable monetization",
    keyMetrics: "$1.5M raised · 100k downloads · became meme · 2015 wind-down",
  },
  {
    id: 70,
    name: "Biz Stone's (Multiple Pivots)",
    yearRange: "2015–2018",
    description: "Built Jelly (mobile Q&A), Blocktogether (Twitter spam filter), multiple pivots. Founder reputation couldn't overcome weak product strategy. Eventually acquired then shut down.",
    category: "technology",
    sector: "Social / Utilities",
    tags: ["Multiple Pivots", "Founder Reputation"],
    failureReason: "Founder reputation doesn't overcome product-market fit issues + constant pivoting",
    keyMetrics: "$5M+ raised · <1M users · acquired and mothballed",
  },
  {
    id: 71,
    name: "YikYak",
    yearRange: "2013–2017",
    description: "Anonymous local messaging app. 5M users, $200M valuation, but enabled cyberbullying + harassment at schools. Faced regulatory pressure + reputation damage. Shut down.",
    category: "technology",
    sector: "Social / Messaging",
    tags: ["Anonymous", "Social", "Bullying", "Regulation"],
    failureReason: "Anonymous platform = harassment platform. Regulatory + reputation risk too high",
    keyMetrics: "5M users · $200M valuation · 2017 shutdown + school bans",
  },
  {
    id: 72,
    name: "Sovrn (ad tech pivot)",
    yearRange: "2005–present",
    description: "Started as Conversant (online advertising). Pivoted to blockchain ad network. Neither product found sustainable unit economics. Continuously bleeding cash.",
    category: "technology",
    sector: "AdTech / Blockchain",
    tags: ["AdTech", "Blockchain", "Pivot", "Unit Economics"],
    failureReason: "AdTech unit economics broken + blockchain pivot irrelevant + continuous pivoting",
    keyMetrics: "$100M+ raised · persistently unprofitable · now penny stock",
  },
  {
    id: 73,
    name: "Digg",
    yearRange: "2004–2010+",
    description: "Social news aggregator. Had 30M users, beat Reddit and Slashdot. Redesign in 2010 (v4) alienated users overnight. All users migrated to Reddit. Never recovered.",
    category: "technology",
    sector: "Social / News",
    tags: ["Social", "News", "Product Redesign", "User Migration"],
    failureReason: "Single redesign killed by user revolt + failed to retain community trust",
    keyMetrics: "30M peak users → massive exodus · Reddit captured all refugees",
  },
  {
    id: 74,
    name: "StumbleUpon",
    yearRange: "2003–2018",
    description: "Content discovery engine. 25M users, but couldn't monetize effectively. Sold to eBay for $75M (2007), then back to founders for $5M (2012). Finally shut down 2018.",
    category: "technology",
    sector: "Content Discovery",
    tags: ["Discovery", "Monetization", "Acquisition"],
    failureReason: "Large user base but weak monetization + unprofitable from inception",
    keyMetrics: "25M users · $75M sale to eBay · $5M buyback · 2018 shutdown",
  },
  {
    id: 75,
    name: "Delicious",
    yearRange: "2003–present",
    description: "Social bookmarking service. Acquired by Yahoo, neglected, then sold to new owners 3x. Never found business model. Now zombie product.",
    category: "technology",
    sector: "Web Tools / Social",
    tags: ["Social Bookmarking", "Zombie", "Acquisitions"],
    failureReason: "Yahoo killed it through neglect, multiple failed acquisitions couldn't save it",
    keyMetrics: "5M users (peak) · $30M revenue at peak · now mostly defunct",
  },
  {
    id: 76,
    name: "Thumbtack (near death)",
    yearRange: "2008–2024+",
    description: "Service marketplace (contractors). Raised $300M+, valued at $3B, but never profitable. Losses from customer acquisition + marketplace arbitrage continue. Stuck in zombie zone.",
    category: "markets",
    sector: "Marketplace / Services",
    tags: ["Marketplace", "Services", "Unit Economics"],
    failureReason: "Marketplace arbitrage economics: CAC too high relative to transaction value",
    keyMetrics: "$300M+ raised · $3B valuation · perpetually unprofitable · 16-year runway",
  },
  {
    id: 77,
    name: "Airbnb (near death 2009)",
    yearRange: "2008–2024+",
    description: "Only survived because founders slept at YC, begged for money, and refused to give up. Today worth $100B+ but took 7+ years to profitability.",
    category: "markets",
    sector: "Travel / Hospitality",
    tags: ["Travel", "Marketplace", "Resilience"],
    failureReason: "Nearly died from: legal battles, regulatory hostility, and razor-thin margins for years",
    keyMetrics: "Took 7 years to profitability · $100B+ today · legal battles ongoing",
  },
  {
    id: 78,
    name: "Jawbone",
    yearRange: "2011–2017",
    description: "Wearable fitness tracker. Raised $200M+, but competition from Fitbit + Apple Watch destroyed the category. Refused to pivot and stuck with single product.",
    category: "technology",
    sector: "Consumer Hardware / Wearables",
    tags: ["Wearables", "Hardware", "Competition"],
    failureReason: "Stuck in single product while category disrupted by Apple Watch + Fitbit",
    keyMetrics: "$200M+ raised · $2B valuation · 2017 shutdown",
  },
  {
    id: 79,
    name: "Doxy.me",
    yearRange: "2013–present",
    description: "Telemedicine platform. Raised $25M but crushed by COVID lockdown competition (Zoom, Google Meet free). Never found sustainable differentiation.",
    category: "health",
    sector: "Healthtech / Telemedicine",
    tags: ["Telemedicine", "Health", "Competition"],
    failureReason: "Generic telemedicine platform destroyed by free tools (Zoom, Google Meet)",
    keyMetrics: "$25M raised · limited users · profitable but capped growth",
  },
  {
    id: 80,
    name: "Bulu Box",
    yearRange: "2011–2017",
    description: "Health supplement subscription box. Raised $5M, hundreds of thousands of subscribers, but margins killed by fulfillment + low LTV. Couldn't achieve unit economics.",
    category: "health",
    sector: "Subscription / E-commerce",
    tags: ["Subscription", "Health", "Unit Economics"],
    failureReason: "Subscription model + physical fulfillment = unit economics too weak",
    keyMetrics: "$5M raised · 100k+ subscribers · 2017 shutdown",
  },
  {
    id: 81,
    name: "Thrive Market",
    yearRange: "2014–present",
    description: "Organic grocery membership. Raised $100M+, $1B+ valuation, but unit economics remain broken. Heavy losses on fulfillment + organic margins too thin.",
    category: "markets",
    sector: "Grocery / E-commerce",
    tags: ["Grocery", "Organic", "Unit Economics"],
    failureReason: "Organic grocery margins + fulfillment costs + high CAC = unsustainable model",
    keyMetrics: "$100M+ raised · $1B+ valuation · perpetually unprofitable · zombie company",
  },
  {
    id: 82,
    name: "Birchbox",
    yearRange: "2011–present",
    description: "Subscription beauty box. Raised $80M+, seemed unstoppable, but high CAC + low LTV + fulfillment costs destroyed unit economics.",
    category: "markets",
    sector: "Subscription / Beauty",
    tags: ["Subscription", "Beauty", "Unit Economics"],
    failureReason: "Subscription model + physical fulfillment + acquisition-dependent = broken economics",
    keyMetrics: "$80M+ raised · peak 500k subscribers · profitable but capped",
  },
  {
    id: 83,
    name: "Orbotix (Sphero)",
    yearRange: "2010–2014",
    description: "Robotic ball toy. Raised $15M, cool product, but toy market too competitive + seasonality + low LTV killed it.",
    category: "technology",
    sector: "Consumer Hardware / Toys",
    tags: ["Hardware", "Toys", "Seasonal"],
    failureReason: "Hardware toy market too competitive + seasonal demand + low lifetime value",
    keyMetrics: "$15M raised · sold to Hasbro 2014 but marginalized",
  },
  {
    id: 84,
    name: "Uber Freight (zombie)",
    yearRange: "2017–present",
    description: "Uber tried to disrupt trucking logistics. Massive burn rate, no unit economics, regulatory battles with truckers. Became an internal zombie project.",
    category: "markets",
    sector: "Logistics / Transportation",
    tags: ["Logistics", "Unit Economics", "Regulation"],
    failureReason: "Logistics unit economics broken + regulatory battles + independent contractor issues",
    keyMetrics: "$1B+ spent · still unprofitable · perpetually burning cash",
  },
  {
    id: 85,
    name: "Munchery",
    yearRange: "2013–2018",
    description: "Meal delivery startup. Raised $50M, 100k+ daily orders, but food costs + delivery logistics + driver arbitrage made it unsustainable.",
    category: "markets",
    sector: "Food Delivery",
    tags: ["Food Delivery", "Unit Economics", "Logistics"],
    failureReason: "Food delivery unit economics: COGS + delivery logistics + driver arbitrage = loss per order",
    keyMetrics: "$50M raised · 100k orders/day · 2018 shutdown",
  },
  {
    id: 86,
    name: "Sidecar",
    yearRange: "2012–2015",
    description: "Ride-sharing app (competitor to Uber/Lyft). Raised $12M, had 200k+ users in 2 cities, but couldn't compete with Uber's $40B+. Lost the burn war.",
    category: "markets",
    sector: "Ride-Sharing / Transportation",
    tags: ["Ride-Sharing", "Uber", "Burn War"],
    failureReason: "Outburned by Uber. Can't win crowded market without unlimited capital.",
    keyMetrics: "$12M raised · 200k users · 2015 shutdown · Uber won by burning $20B",
  },
  {
    id: 87,
    name: "Blade (again/Halo)",
    yearRange: "2014–2023",
    description: "Urban air mobility (helicopter NYC). Raised $100M+, looked like future of transport, but unprofitable, safety concerns + FAA delays killed it.",
    category: "technology",
    sector: "Transportation / Aerospace",
    tags: ["Aerospace", "Urban Mobility", "Regulation"],
    failureReason: "Unit economics impossible + regulatory delays + safety liability + tiny addressable market",
    keyMetrics: "$100M+ raised · 2023 bankruptcy · never achieved scale",
  },
  {
    id: 88,
    name: "TaskRabbit (Amazon integration near death)",
    yearRange: "2008–2024+",
    description: "On-demand task marketplace. Acquired by Amazon for $615M, but suffered integration failures + lost momentum + gig classification battles.",
    category: "markets",
    sector: "Gig / On-Demand",
    tags: ["Gig Economy", "Marketplace", "Amazon"],
    failureReason: "Post-acquisition: integration struggles + gig worker classification pressure",
    keyMetrics: "$615M acquisition · profits elusive · labor disputes ongoing",
  },
];

